name: Update Asana task on PR merge
on:
  pull_request:
    types:
      - opened
      - closed

env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
  R_MY_SECRET: ${{ secrets.R_MY_SECRET }}

jobs:
  transition-section:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR description
        id: check
        run: echo "PR description ${{ github.event.pull_request.body }}"
      - name: Print secret
        id: pesecret
        run: echo "secret for dev environment $MY_SECRET"        
      - name: Print repo secret
        id: prsecret
        run: echo "secret for repo ${{ env.R_MY_SECRET }}"        
      - name: Print variable env
        id: penvvar
        run: echo "var for env ${MY_VARIABLE}"        
      - name: Print variable for repo
        id: prvar
        run: echo "var for repo $R_MY_VAR"        
