name: Update Asana task on PR merge
on:
  pull_request:
    types:
      - opened
      - closed


jobs:
  transition-section:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR description
        id: check
        run: echo "PR description ${{ github.event.pull_request.body }}"
