name: Update Asana task on PR merge
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - closed
      - reopened
  
env:
  ASANA_APP_URL: "https://app.asana.com"
  ASANA_GOPHERS_SECTION_IN_STAGING: "1207386778091330"

jobs:
  update-section-in-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke API
        continue-on-error: true
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}        
        run: |
          echo "processing description:"
          echo "${PR_DESCRIPTION}"
          # extract the task id from the PR description, this is a best effort and may fail
          # if the footer of the description is not formatted according to https://asana.com/apps/github,
          # that is: https://app.asana.com/0/<projectID>/<taskId>
          # TODO: add support for multiple tasks in the same PR description
          ASANA_TASK_ID=$(echo "${PR_DESCRIPTION}" | grep ${{ env.ASANA_APP_URL }} | awk -F"/" '{print $NF}')
          echo "Updating task with id ${ASANA_TASK_ID} to section: In Staging"
          curl -s --request POST \
               --url ${{ env.ASANA_APP_URL }}/api/1.0/sections/${{ env.ASANA_GOPHERS_SECTION_IN_STAGING }}/addTask \
               --header 'accept: application/json' \
               --header 'authorization: Bearer '${{ secrets.ASANA_TOKEN }} \
               --header 'content-type: application/json' \
               --data '{ "data": {"task": "'${ASANA_TASK_ID}'"} }' || {
                 echo "error updating task with id ${ASANA_TASK_ID}"
                 return 1
               }
           echo "Successfully updated task with id ${ASANA_TASK_ID}"
