name: Update Asana task on PR merge
on:
  pull_request:
    types:
      - opened
      - closed

env:
  ASANA_GOPHERS_SECTION_CODE_REVIEW: "1207386778091330"
  R_MY_SECRET: ${{ secrets.ASANA_TOKEN }}

jobs:
  transition-section:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR description
        id: check
        run: echo "PR description ${{ github.event.pull_request.body }}"
      - name: Print var
        id: pesecret
        run: echo "secret for  environment $ASANA_GOPHERS_SECTION_CODE_REVIEW"        
      - name: Print var using env.
        id: prsecret
        run: echo "secret for repo ${{ env.ASANA_GOPHERS_SECTION_CODE_REVIEW }}"            
      - name: call asana api
        run: |
          npm install
          curl --request POST \
               --url https://app.asana.com/api/1.0/sections/$ASANA_GOPHERS_SECTION_CODE_REVIEW/addTask \
               --header 'accept: application/json' \
               --header 'authorization: Bearer '${{ secrets.ASANA_TOKEN }} \
               --header 'content-type: application/json' \
               --data '{ "data": {"task": "1207386778091342"} }'
